services:
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
        
  assistant-core:
    build:
      context: .
      dockerfile: AssistantCore/Dockerfile
    ports:
      - 5264:5264
    environment:
      - USE_SEQ=true
      - USE_FILE_LOGGING=true
      - SEQ_URL=http://seq:5341
      - LOG_DIRECTORY=logs
      - MINIMUM_LOG_LEVEL=Debug
    depends_on:
      - seq