services:
  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    networks:
      - aiassistant
        
  core:
    build:
      context: .
      dockerfile: AssistantCore/Dockerfile
    ports:
      - 5264:5264
    environment:
      - USE_FILE_LOGGING=false
      - SEQ_URL=http://seq:5341
      - MINIMUM_LOG_LEVEL=Debug
    networks:
      - aiassistant
    depends_on:
      - seq

networks:
  aiassistant:
    external: true
